/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BakylauRouteImport } from './routes/bakylau'
import { Route as KartaRouteImport } from './routes/karta'
import { Route as OtinishRouteImport } from './routes/otinish'
import { Route as VolonterRouteImport } from './routes/volonter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BakylauRoute = BakylauRouteImport.update({
  id: '/bakylau',
  path: '/bakylau',
  getParentRoute: () => rootRouteImport,
} as any)
const KartaRoute = KartaRouteImport.update({
  id: '/karta',
  path: '/karta',
  getParentRoute: () => rootRouteImport,
} as any)
const OtinishRoute = OtinishRouteImport.update({
  id: '/otinish',
  path: '/otinish',
  getParentRoute: () => rootRouteImport,
} as any)
const VolonterRoute = VolonterRouteImport.update({
  id: '/volonter',
  path: '/volonter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bakylau': typeof BakylauRoute
  '/karta': typeof KartaRoute
  '/otinish': typeof OtinishRoute
  '/volonter': typeof VolonterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bakylau': typeof BakylauRoute
  '/karta': typeof KartaRoute
  '/otinish': typeof OtinishRoute
  '/volonter': typeof VolonterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bakylau': typeof BakylauRoute
  '/karta': typeof KartaRoute
  '/otinish': typeof OtinishRoute
  '/volonter': typeof VolonterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/bakylau' | '/karta' | '/otinish' | '/volonter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/bakylau' | '/karta' | '/otinish' | '/volonter'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bakylau'
    | '/karta'
    | '/otinish'
    | '/volonter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BakylauRoute: typeof BakylauRoute
  KartaRoute: typeof KartaRoute
  OtinishRoute: typeof OtinishRoute
  VolonterRoute: typeof VolonterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakylau': {
      id: '/bakylau'
      path: '/bakylau'
      fullPath: '/bakylau'
      preLoaderRoute: typeof BakylauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karta': {
      id: '/karta'
      path: '/karta'
      fullPath: '/karta'
      preLoaderRoute: typeof KartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otinish': {
      id: '/otinish'
      path: '/otinish'
      fullPath: '/otinish'
      preLoaderRoute: typeof OtinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volonter': {
      id: '/volonter'
      path: '/volonter'
      fullPath: '/volonter'
      preLoaderRoute: typeof VolonterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BakylauRoute: BakylauRoute,
  KartaRoute: KartaRoute,
  OtinishRoute: OtinishRoute,
  VolonterRoute: VolonterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
